[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[profile.dev]
incremental = true
lto = false

[profile.release]
incremental = true
lto = false

[dependencies]
anyhow = "1.0.95"
libc = "0.2.169"
frontend = { version = "0.1.0", path = "../frontend" }
