[package]
name = "args"
version = "0.1.0"
edition = "2021"

[profile.dev]
incremental = true
lto = false

[profile.release]
incremental = true
lto = false

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }
